{{- if .Values.azureKeyVaultSecrets.enabled }}
{{- range .Values.azureKeyVaultSecrets.items }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ printf "%s-sync" .kubernetesSecretName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "migration-intake.labels" $ | nindent 4 }}
spec:
  vault:
    name: {{ $.Values.azureKeyVaultSecrets.vaultName | quote }}
    object:
      name: {{ .akvSecretName | quote }}
      type: {{ default "secret" .objectType | quote }}
  output:
    secret:
      name: {{ .kubernetesSecretName | quote }}
      type: Opaque
      dataKey: {{ .envName | quote }}
{{- end }}
{{- end }}
{{- if .Values.ingress.azureKeyVaultCertificates.enabled }}
{{- range .Values.ingress.azureKeyVaultCertificates.items }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ printf "%s-sync" .kubernetesSecretName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "migration-intake.labels" $ | nindent 4 }}
spec:
  vault:
    name: {{ $.Values.ingress.azureKeyVaultCertificates.vaultName | quote }}
    object:
      name: {{ .akvCertificateName | quote }}
      type: certificate
  output:
    secret:
      name: {{ .kubernetesSecretName | quote }}
      type: kubernetes.io/tls
{{- end }}
{{- end }}