"""
Email Notification Service — Production-Ready Alert Notifications.

Supports:
- SMTP email delivery with TLS/SSL
- SendGrid integration for enterprise delivery
- Microsoft Graph API for Office 365
- Email templates with HTML formatting
- Retry logic with exponential backoff
- Notification history tracking
- Synapse Checksum Report notifications
"""

import asyncio
import smtplib
import ssl
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.database import AlertNotificationHistory

logger = structlog.get_logger(__name__)


# ── Email Templates ────────────────────────────────────────────────────

VM_THRESHOLD_ALERT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background: {header_color}; color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
        .header h1 {{ margin: 0; font-size: 24px; }}
        .content {{ background: #f9fafb; padding: 20px; border: 1px solid #e5e7eb; }}
        .alert-box {{ background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid {border_color}; }}
        .metric {{ font-size: 32px; font-weight: bold; color: {metric_color}; }}
        .threshold {{ color: #6b7280; font-size: 14px; }}
        .details {{ margin-top: 16px; }}
        .details table {{ width: 100%; border-collapse: collapse; }}
        .details td {{ padding: 8px; border-bottom: 1px solid #e5e7eb; }}
        .details td:first-child {{ font-weight: 600; width: 40%; }}
        .action-btn {{ display: inline-block; background: #3b82f6; color: white; padding: 12px 24px;
                      text-decoration: none; border-radius: 6px; margin-top: 16px; }}
        .footer {{ background: #f3f4f6; padding: 16px; border-radius: 0 0 8px 8px; font-size: 12px; color: #6b7280; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>⚠️ VM Threshold Alert: {severity}</h1>
        </div>
        <div class="content">
            <div class="alert-box">
                <h2>{vm_name}</h2>
                <div class="metric">{metric_type}: {current_value}%</div>
                <div class="threshold">Threshold: {threshold_value}%</div>
            </div>

            <div class="details">
                <table>
                    <tr><td>Resource Group</td><td>{resource_group}</td></tr>
                    <tr><td>Subscription</td><td>{subscription_id}</td></tr>
                    <tr><td>Alert Time</td><td>{alert_time}</td></tr>
                    <tr><td>Severity</td><td>{severity}</td></tr>
                </table>
            </div>

            <a href="{portal_url}" class="action-btn">View in Portal</a>
        </div>
        <div class="footer">
            <p>This alert was generated by ATTCC Infrastructure Alert System.</p>
            <p>To manage your alert preferences, visit the <a href="{settings_url}">Infra Alerts Settings</a>.</p>
        </div>
    </div>
</body>
</html>
"""

EXPIRY_ALERT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background: {header_color}; color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
        .header h1 {{ margin: 0; font-size: 24px; }}
        .content {{ background: #f9fafb; padding: 20px; border: 1px solid #e5e7eb; }}
        .alert-box {{ background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid {border_color}; }}
        .expiry {{ font-size: 32px; font-weight: bold; color: {expiry_color}; }}
        .resource {{ color: #111827; font-size: 18px; font-weight: 600; margin-bottom: 8px; }}
        .details {{ margin-top: 16px; }}
        .details table {{ width: 100%; border-collapse: collapse; }}
        .details td {{ padding: 8px; border-bottom: 1px solid #e5e7eb; }}
        .details td:first-child {{ font-weight: 600; width: 40%; }}
        .action-btn {{ display: inline-block; background: #3b82f6; color: white; padding: 12px 24px;
                      text-decoration: none; border-radius: 6px; margin-top: 16px; }}
        .footer {{ background: #f3f4f6; padding: 16px; border-radius: 0 0 8px 8px; font-size: 12px; color: #6b7280; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔔 Expiry Alert: {alert_type_label}</h1>
        </div>
        <div class="content">
            <div class="alert-box">
                <div class="resource">{resource_name}</div>
                <div class="expiry">{days_until_expiry} days until expiry</div>
                <div style="color: #6b7280; font-size: 14px;">Expires: {expiry_date}</div>
            </div>

            <div class="details">
                <table>
                    <tr><td>Alert Type</td><td>{alert_type_label}</td></tr>
                    <tr><td>Resource ID</td><td>{resource_identifier}</td></tr>
                    <tr><td>Description</td><td>{description}</td></tr>
                    <tr><td>Severity</td><td>{severity}</td></tr>
                    <tr><td>Alert Time</td><td>{alert_time}</td></tr>
                </table>
            </div>
            <a href="{action_url}" class="action-btn">Take Action</a>
        </div>
        <div class="footer">
            <p>This alert was generated by ATTCC Infrastructure Alert System.</p>
            <p>Please renew or update this resource before the expiry date to avoid service interruption.</p>
        </div>
    </div>
</body>
</html>
"""


STORAGE_ALERT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background: {header_color}; color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
        .header h1 {{ margin: 0; font-size: 24px; }}
        .content {{ background: #f9fafb; padding: 20px; border: 1px solid #e5e7eb; }}
        .alert-box {{ background: white; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid {border_color}; }}
        .metric {{ font-size: 32px; font-weight: bold; color: {metric_color}; }}
        .threshold {{ color: #6b7280; font-size: 14px; }}
        .details {{ margin-top: 16px; }}
        .details table {{ width: 100%; border-collapse: collapse; }}
        .details td {{ padding: 8px; border-bottom: 1px solid #e5e7eb; }}
        .details td:first-child {{ font-weight: 600; width: 40%; }}
        .action-btn {{ display: inline-block; background: #3b82f6; color: white; padding: 12px 24px;
                      text-decoration: none; border-radius: 6px; margin-top: 16px; }}
        .footer {{ background: #f3f4f6; padding: 16px; border-radius: 0 0 8px 8px; font-size: 12px; color: #6b7280; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Storage Alert: {severity}</h1>
        </div>
        <div class="content">
            <div class="alert-box">
                <h2>{account_name}</h2>
                <div class="metric">{metric_type}: {current_value}</div>
                <div class="threshold">Threshold: {threshold_value}</div>
            </div>

            <div class="details">
                <table>
                    <tr><td>Resource Group</td><td>{resource_group}</td></tr>
                    <tr><td>Subscription</td><td>{subscription_id}</td></tr>
                    <tr><td>Alert Time</td><td>{alert_time}</td></tr>
                    <tr><td>Severity</td><td>{severity}</td></tr>
                </table>
            </div>
            <a href="{portal_url}" class="action-btn">View in Portal</a>
        </div>
        <div class="footer">
            <p>This alert was generated by ATTCC Infrastructure Alert System.</p>
            <p>To manage your alert preferences, visit the <a href="{settings_url}">Infra Alerts Settings</a>.</p>
        </div>
    </div>
</body>
</html>
"""


class EmailNotificationService:
    """
    Production-ready email notification service.

    Supports multiple delivery methods:
    - SMTP (default)
    - SendGrid (enterprise)
    - Microsoft Graph API (Office 365)
    """

    def __init__(self, db_session: AsyncSession | None = None):
        self.db = db_session
        self.smtp_host = getattr(settings, "SMTP_HOST", "mta01.az.3pc.att.com")
        self.smtp_port = int(getattr(settings, "SMTP_PORT", 587))
        self.smtp_user = getattr(settings, "SMTP_USER", "")
        self.smtp_password = getattr(settings, "SMTP_PASSWORD", "")
        self.smtp_from = getattr(settings, "SMTP_FROM_ADDRESS", "m55663-ap@mta01.att-mail.com")
        self.smtp_use_tls = getattr(settings, "SMTP_USE_TLS", True)
        self.sendgrid_api_key = getattr(settings, "SENDGRID_API_KEY", "")
        self.portal_base_url = getattr(settings, "PORTAL_BASE_URL", "http://localhost:5177")
        self.max_retries = 3
        self.retry_delay = 2

    async def send_vm_threshold_alert(
        self,
        recipient_emails: list[str],
        vm_name: str,
        resource_group: str,
        subscription_id: str,
        metric_type: str,
        current_value: float,
        threshold_value: float,
        severity: str,
        alert_id: int,
    ) -> dict[str, Any]:
        """Send VM threshold alert notification."""
        colors = self._get_severity_colors(severity)

        subject = f"[{severity.upper()}] VM Alert: {vm_name} - {metric_type.upper()} at {current_value}%"

        html_body = VM_THRESHOLD_ALERT_TEMPLATE.format(
            vm_name=vm_name,
            resource_group=resource_group,
            subscription_id=subscription_id,
            metric_type=metric_type.upper(),
            current_value=current_value,
            threshold_value=threshold_value,
            severity=severity.upper(),
            alert_time=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
            header_color=colors["header"],
            border_color=colors["border"],
            metric_color=colors["metric"],
            portal_url=f"{self.portal_base_url}/infra-alerts?alert={alert_id}",
            settings_url=f"{self.portal_base_url}/infra-alerts?tab=configs",
        )

        results = await self._send_email_batch(
            recipient_emails=recipient_emails,
            subject=subject,
            html_body=html_body,
            alert_type="vm_threshold",
            alert_id=alert_id,
        )

        return {
            "alert_id": alert_id,
            "recipients": len(recipient_emails),
            "success": sum(1 for r in results if r["status"] == "sent"),
            "failed": sum(1 for r in results if r["status"] == "failed"),
            "results": results,
        }

    async def send_expiry_alert(
        self,
        recipient_emails: list[str],
        resource_name: str,
        resource_identifier: str,
        alert_type: str,
        expiry_date: datetime,
        days_until_expiry: int,
        severity: str,
        description: str | None,
        alert_id: int,
    ) -> dict[str, Any]:
        """Send expiry alert notification."""
        colors = self._get_severity_colors(severity)
        alert_type_labels = {
            "mech_id": "MechID Account",
            "certificate": "Certificate",
            "aaf_account": "AAF Account",
            "database_account": "Database Account",
            "itservices_domain": "ITServices Domain Account",
        }
        alert_type_label = alert_type_labels.get(alert_type, alert_type)

        if days_until_expiry <= 0:
            subject = f"[EXPIRED] {alert_type_label}: {resource_name} has expired!"
        else:
            subject = f"[{severity.upper()}] {alert_type_label}: {resource_name} expires in {days_until_expiry} days"

        html_body = EXPIRY_ALERT_TEMPLATE.format(
            resource_name=resource_name,
            resource_identifier=resource_identifier,
            alert_type_label=alert_type_label,
            expiry_date=expiry_date.strftime("%Y-%m-%d"),
            days_until_expiry=days_until_expiry if days_until_expiry > 0 else "EXPIRED",
            severity=severity.upper(),
            description=description or "N/A",
            alert_time=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
            header_color=colors["header"],
            border_color=colors["border"],
            expiry_color=colors["metric"],
            action_url=f"{self.portal_base_url}/infra-alerts?alert={alert_id}",
        )

        results = await self._send_email_batch(
            recipient_emails=recipient_emails,
            subject=subject,
            html_body=html_body,
            alert_type="custom_expiry",
            alert_id=alert_id,
        )

        return {
            "alert_id": alert_id,
            "recipients": len(recipient_emails),
            "success": sum(1 for r in results if r["status"] == "sent"),
            "failed": sum(1 for r in results if r["status"] == "failed"),
            "results": results,
        }

    async def send_storage_alert(
        self,
        recipient_emails: list[str],
        account_name: str,
        resource_group: str,
        subscription_id: str,
        metric_type: str,
        current_value: str,
        threshold_value: str,
        severity: str,
        alert_id: int,
    ) -> dict[str, Any]:
        """Send storage alert notification."""
        colors = self._get_severity_colors(severity)

        subject = f"[{severity.upper()}] Storage Alert: {account_name} - {metric_type} threshold exceeded"

        html_body = STORAGE_ALERT_TEMPLATE.format(
            account_name=account_name,
            resource_group=resource_group,
            subscription_id=subscription_id,
            metric_type=metric_type,
            current_value=current_value,
            threshold_value=threshold_value,
            severity=severity.upper(),
            alert_time=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
            header_color=colors["header"],
            border_color=colors["border"],
            metric_color=colors["metric"],
            portal_url=f"{self.portal_base_url}/infra-alerts?alert={alert_id}",
            settings_url=f"{self.portal_base_url}/infra-alerts?tab=configs",
        )

        results = await self._send_email_batch(
            recipient_emails=recipient_emails,
            subject=subject,
            html_body=html_body,
            alert_type="storage",
            alert_id=alert_id,
        )

        return {
            "alert_id": alert_id,
            "recipients": len(recipient_emails),
            "success": sum(1 for r in results if r["status"] == "sent"),
            "failed": sum(1 for r in results if r["status"] == "failed"),
            "results": results,
        }

    async def send_alert_digest(
        self,
        recipient_emails: list[str],
        vm_alerts: list[dict],
        expiry_alerts: list[dict],
    ) -> dict[str, Any]:
        """Send daily digest of all active alerts."""
        total_alerts = len(vm_alerts) + len(expiry_alerts)

        if total_alerts == 0:
            return {"status": "skipped", "reason": "no_active_alerts"}

        vm_rows = "\n".join(
            [
                f"<tr><td>{a['vm_name']}</td><td>{a['metric_type'].upper()}</td>"
                f"<td>{a['current_value']}%</td><td>{a['severity']}</td></tr>"
                for a in vm_alerts[:10]
            ]
        )

        expiry_rows = "\n".join(
            [
                f"<tr><td>{a['resource_name']}</td><td>{a['alert_type']}</td>"
                f"<td>{a['days_until_expiry']} days</td><td>{a['severity']}</td></tr>"
                for a in expiry_alerts[:10]
            ]
        )

        html_body = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', Arial, sans-serif; }}
                .container {{ max-width: 700px; margin: 0 auto; padding: 20px; }}
                .header {{ background: #1e40af; color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
                .content {{ background: #f9fafb; padding: 20px; }}
                table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
                th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #e5e7eb; }}
                th {{ background: #f3f4f6; font-weight: 600; }}
                .section-title {{ font-size: 18px; font-weight: 600; margin: 16px 0 8px; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>📊 Daily Infrastructure Alert Digest</h1>
                    <p style="margin: 8px 0 0; opacity: 0.9;">{datetime.utcnow().strftime("%Y-%m-%d")}</p>
                </div>
                <div class="content">
                    <p>You have <strong>{total_alerts}</strong> active infrastructure alerts requiring attention.</p>

                    {"<div class='section-title'>🖥️ VM Threshold Alerts (" + str(len(vm_alerts)) + ")</div><table><tr><th>VM</th><th>Metric</th><th>Value</th><th>Severity</th></tr>" + vm_rows + "</table>" if vm_alerts else ""}

                    {"<div class='section-title'>📅 Expiry Alerts (" + str(len(expiry_alerts)) + ")</div><table><tr><th>Resource</th><th>Type</th><th>Expires In</th><th>Severity</th></tr>" + expiry_rows + "</table>" if expiry_alerts else ""}

                          <a href="{self.portal_base_url}/infra-alerts"
                                  style="display: inline-block; background: #3b82f6; color: white; padding: 12px 24px;
                              text-decoration: none; border-radius: 6px; margin-top: 16px;">
                        View All Alerts
                    </a>
                </div>
            </div>
        </body>
        </html>
        """

        subject = f"[Digest] {total_alerts} Active Infrastructure Alerts - {datetime.utcnow().strftime('%Y-%m-%d')}"

        results = await self._send_email_batch(
            recipient_emails=recipient_emails,
            subject=subject,
            html_body=html_body,
            alert_type="digest",
            alert_id=0,
        )

        return {
            "total_alerts": total_alerts,
            "recipients": len(recipient_emails),
            "success": sum(1 for r in results if r["status"] == "sent"),
        }

    async def send_alert_status_change(
        self,
        recipient_emails: list[str],
        alert_type: str,
        resource_name: str,
        action: str,
        action_by: str,
        alert_id: int,
        extra_details: dict | None = None,
    ) -> dict[str, Any]:
        """Send notification email when an alert is acknowledged or resolved."""
        if not recipient_emails:
            return {"status": "skipped", "reason": "no_recipients"}

        action_label = "Acknowledged" if action == "acknowledged" else "Resolved"
        action_color = "#2563eb" if action == "acknowledged" else "#16a34a"
        icon = "✅" if action == "acknowledged" else "✔️"

        extra_rows = "".join(
            f"<tr><td>{k.replace('_', ' ').title()}</td><td>{v}</td></tr>" for k, v in (extra_details or {}).items()
        )

        html_body = f"""
<!DOCTYPE html>
<html>
<head>
  <style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; }}
    .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
    .header {{ background: {action_color}; color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
    .header h1 {{ margin: 0; font-size: 22px; }}
    .content {{ background: #f9fafb; padding: 20px; border: 1px solid #e5e7eb; }}
    .info-box {{ background: white; border-radius: 8px; padding: 16px; margin: 12px 0; border-left: 4px solid {action_color}; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
    td {{ padding: 8px; border-bottom: 1px solid #e5e7eb; }}
    td:first-child {{ font-weight: 600; width: 40%; }}
    .footer {{ background: #f3f4f6; padding: 12px 16px; border-radius: 0 0 8px 8px; font-size: 12px; color: #6b7280; }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>{icon} Alert {action_label}: {resource_name}</h1>
    </div>
    <div class="content">
      <div class="info-box">
        <p style="margin:0;font-size:15px;">
          The following infrastructure alert has been <strong>{action_label.lower()}</strong>.
        </p>
      </div>
      <table>
        <tr><td>Resource</td><td>{resource_name}</td></tr>
        <tr><td>Alert Type</td><td>{alert_type.replace("_", " ").title()}</td></tr>
        <tr><td>Action</td><td>{action_label}</td></tr>
        <tr><td>Performed By</td><td>{action_by}</td></tr>
        <tr><td>Time</td><td>{datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")}</td></tr>
        {extra_rows}
      </table>
      <a href="{self.portal_base_url}/infra-alerts"
         style="display:inline-block;background:{action_color};color:white;padding:10px 22px;
                text-decoration:none;border-radius:6px;margin-top:16px;">
        View Infra Alerts
      </a>
    </div>
    <div class="footer">
      <p>This notification was sent by the ATTCC Infrastructure Alert System.</p>
    </div>
  </div>
</body>
</html>
"""

        subject = f"[{action_label.upper()}] Infra Alert: {resource_name}"

        results = await self._send_email_batch(
            recipient_emails=recipient_emails,
            subject=subject,
            html_body=html_body,
            alert_type=alert_type,
            alert_id=alert_id,
        )

        return {
            "alert_id": alert_id,
            "action": action,
            "recipients": len(recipient_emails),
            "success": sum(1 for r in results if r["status"] == "sent"),
            "failed": sum(1 for r in results if r["status"] == "failed"),
        }

    async def _send_email_batch(
        self,
        recipient_emails: list[str],
        subject: str,
        html_body: str,
        alert_type: str,
        alert_id: int,
    ) -> list[dict[str, Any]]:
        """Send email to multiple recipients with retry logic."""
        results = []

        for email in recipient_emails:
            result = await self._send_single_email(
                recipient=email,
                subject=subject,
                html_body=html_body,
            )

            # Record notification history
            await self._record_notification(
                alert_type=alert_type,
                alert_id=alert_id,
                recipient_email=email,
                subject=subject,
                status=result["status"],
                error_message=result.get("error"),
            )

            results.append(
                {
                    "email": email,
                    "status": result["status"],
                    "error": result.get("error"),
                }
            )

        return results

    async def _send_single_email(
        self,
        recipient: str,
        subject: str,
        html_body: str,
    ) -> dict[str, Any]:
        """Send single email with retry logic."""
        for attempt in range(self.max_retries):
            try:
                if self.sendgrid_api_key:
                    return await self._send_via_sendgrid(recipient, subject, html_body)
                return await self._send_via_smtp(recipient, subject, html_body)
            except Exception as e:
                logger.warning(
                    "email_send_retry",
                    attempt=attempt + 1,
                    recipient=recipient,
                    error=str(e),
                )
                if attempt < self.max_retries - 1:
                    await asyncio.sleep(self.retry_delay * (2**attempt))
                else:
                    logger.error("email_send_failed", recipient=recipient, error=str(e))
                    return {"status": "failed", "error": str(e)}

        return {"status": "failed", "error": "Max retries exceeded"}

    async def _send_via_smtp(
        self,
        recipient: str,
        subject: str,
        html_body: str,
    ) -> dict[str, Any]:
        """Send email via SMTP."""
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.smtp_from
        msg["To"] = recipient

        msg.attach(MIMEText(html_body, "html"))

        # Run SMTP in executor to avoid blocking
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, self._smtp_send, msg, recipient)

        logger.info("email_sent_smtp", recipient=recipient, subject=subject[:50])
        return {"status": "sent"}

    def _smtp_send(self, msg: MIMEMultipart, recipient: str) -> None:
        """Synchronous SMTP send (runs in executor)."""
        with smtplib.SMTP(self.smtp_host, self.smtp_port, timeout=30) as server:
            server.ehlo()
            if self.smtp_use_tls:
                # For internal MTA relays, allow self-signed / internal CA certs
                context = ssl.create_default_context()
                context.check_hostname = False
                context.verify_mode = ssl.CERT_NONE
                server.starttls(context=context)
                server.ehlo()
            if self.smtp_user and self.smtp_password:
                server.login(self.smtp_user, self.smtp_password)
            server.sendmail(self.smtp_from, recipient, msg.as_string())

    async def _send_via_sendgrid(
        self,
        recipient: str,
        subject: str,
        html_body: str,
    ) -> dict[str, Any]:
        """Send email via SendGrid API."""
        try:
            import httpx

            async with httpx.AsyncClient() as client:
                response = await client.post(
                    "https://api.sendgrid.com/v3/mail/send",
                    headers={
                        "Authorization": f"Bearer {self.sendgrid_api_key}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "personalizations": [{"to": [{"email": recipient}]}],
                        "from": {"email": self.smtp_from},
                        "subject": subject,
                        "content": [{"type": "text/html", "value": html_body}],
                    },
                    timeout=30.0,
                )

                if response.status_code in (200, 202):
                    logger.info("email_sent_sendgrid", recipient=recipient)
                    return {"status": "sent"}
                error = response.text
                logger.error("sendgrid_error", status=response.status_code, error=error)
                return {"status": "failed", "error": error}
        except ImportError:
            return {"status": "failed", "error": "httpx not installed for SendGrid"}

    async def _record_notification(
        self,
        alert_type: str,
        alert_id: int,
        recipient_email: str,
        status: str,
        subject: str | None = None,
        error_message: str | None = None,
    ) -> None:
        """Record notification in history table."""
        if self.db is None:
            return

        try:
            record = AlertNotificationHistory(
                alert_type=alert_type,
                alert_id=alert_id,
                recipient_email=recipient_email,
                subject=subject,
                notification_method="email",
                status=status,
                error_message=error_message,
            )
            self.db.add(record)
            await self.db.commit()
        except Exception as e:
            logger.error("notification_history_save_failed", error=str(e))
            await self.db.rollback()

    @staticmethod
    def _default_subject(alert_type: str) -> str:
        """Return a human-readable fallback subject for history rows that have no stored subject."""
        labels = {
            "vm_threshold": "VM Threshold Alert",
            "custom_expiry": "Expiry Alert",
            "expiry": "Expiry Alert",
            "storage": "Storage Alert Notification",
            "digest": "Daily Alert Digest",
            "checksum_report": "Checksum Report",
        }
        return labels.get(alert_type, alert_type)

    def _get_severity_colors(self, severity: str) -> dict[str, str]:
        """Get color scheme based on severity."""
        if severity == "critical":
            return {
                "header": "#dc2626",
                "border": "#dc2626",
                "metric": "#dc2626",
            }
        # warning
        return {
            "header": "#d97706",
            "border": "#f59e0b",
            "metric": "#d97706",
        }

    # ──────────────────────────────────────────────────────────────────────
    # SYNAPSE CHECKSUM REPORT EMAILS
    # ──────────────────────────────────────────────────────────────────────

    async def send_checksum_comparison_report(
        self,
        recipient_email: str,
        system: str,  # attcc | ces
        workspace_name: str,
        run_id: str,
        total_pipelines: int,
        changed_count: int,
        added_count: int,
        removed_count: int,
        environment: str = "prod",
        comparison_link: str | None = None,
    ) -> bool:
        """
        Send Synapse checksum comparison report email.

        Args:
            recipient_email: Email recipient
            system: 'attcc' or 'ces'
            workspace_name: Synapse workspace name
            run_id: Checksum run ID
            total_pipelines: Total pipelines checked
            changed_count: Number of changed pipelines
            added_count: Number of added pipelines
            removed_count: Number of removed pipelines
            environment: Environment label
            comparison_link: URL to detailed report

        Returns:
            True if email sent successfully
        """
        try:
            status_emoji = "✅" if (changed_count + added_count + removed_count) == 0 else "⚠️"
            status_text = "No Changes" if (changed_count + added_count + removed_count) == 0 else "Changes Detected"

            subject = f"{status_emoji} Synapse Checksum Report: {system.upper()} - {workspace_name}"

            # HTML template
            html_content = self._render_checksum_html(
                system=system,
                workspace_name=workspace_name,
                run_id=run_id,
                total_pipelines=total_pipelines,
                changed_count=changed_count,
                added_count=added_count,
                removed_count=removed_count,
                environment=environment,
                status_text=status_text,
                status_emoji=status_emoji,
                comparison_link=comparison_link,
            )

            success = False
            send_results = await self._send_email_batch(
                recipient_emails=[recipient_email],
                subject=subject,
                html_body=html_content,
                alert_type="checksum_report",
                alert_id=0,
            )

            if send_results and send_results[0].get("status") == "sent":
                success = True
                logger.info(
                    "checksum_report_sent",
                    recipient=recipient_email,
                    system=system,
                    run_id=run_id,
                )
            return success

        except Exception as exc:
            logger.error(
                "checksum_report_send_failed",
                recipient=recipient_email,
                system=system,
                error=str(exc),
            )
            return False

    def _render_checksum_html(
        self,
        system: str,
        workspace_name: str,
        run_id: str,
        total_pipelines: int,
        changed_count: int,
        added_count: int,
        removed_count: int,
        environment: str,
        status_text: str,
        status_emoji: str,
        comparison_link: str | None = None,
    ) -> str:
        """Render HTML email for checksum report."""
        template_html = """
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #333; }}
                .container {{ max-width: 700px; margin: 0 auto; background: #f9fafb; padding: 20px; }}
                .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }}
                .header h1 {{ margin: 0; font-size: 24px; }}
                .status {{ font-size: 48px; margin: 10px 0; }}
                .content {{ background: white; padding: 30px; border: 1px solid #e5e7eb; }}
                .summary {{ background: #f0f9ff; border-left: 4px solid #0ea5e9; padding: 16px; margin: 16px 0; border-radius: 4px; }}
                .metric {{ display: inline-block; background: white; padding: 16px; margin: 8px; border-radius: 8px; text-align: center; min-width: 120px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
                .metric-number {{ font-size: 32px; font-weight: bold; color: #667eea; }}
                .metric-label {{ font-size: 14px; color: #6b7280; margin-top: 8px; }}
                .metric.changed {{ border-top: 3px solid #f59e0b; }}
                .metric.added {{ border-top: 3px solid #10b981; }}
                .metric.removed {{ border-top: 3px solid #ef4444; }}
                .metric.total {{ border-top: 3px solid #667eea; }}
                .details-table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
                .details-table td {{ padding: 12px; border-bottom: 1px solid #e5e7eb; }}
                .details-table td:first-child {{ font-weight: 600; width: 200px; color: #667eea; }}
                .action-btn {{ display: inline-block; background: #667eea; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin-top: 20px; }}
                .action-btn:hover {{ background: #764ba2; }}
                .footer {{ background: #f3f4f6; padding: 20px; border-radius: 0 0 8px 8px; font-size: 12px; color: #6b7280; text-align: center; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>{status_emoji} Synapse Checksum Report</h1>
                    <div class="status">{status_text}</div>
                </div>
                <div class="content">
                    <div class="summary">
                        <strong>Run Summary:</strong><br/>
                        System: <strong>{system_upper}</strong> | Workspace: <strong>{workspace_name}</strong><br/>
                        Environment: <strong>{environment_upper}</strong> | Run ID: <code>{run_id}</code><br/>
                        Generated: <strong>{timestamp}</strong>
                    </div>

                    <h2>Checksum Statistics</h2>
                    <div style="text-align: center; margin: 20px 0;">
                        <div class="metric total">
                            <div class="metric-number">{total_pipelines}</div>
                            <div class="metric-label">Total Pipelines</div>
                        </div>
                        <div class="metric changed">
                            <div class="metric-number">{changed_count}</div>
                            <div class="metric-label">Changed</div>
                        </div>
                        <div class="metric added">
                            <div class="metric-number">{added_count}</div>
                            <div class="metric-label">Added</div>
                        </div>
                        <div class="metric removed">
                            <div class="metric-number">{removed_count}</div>
                            <div class="metric-label">Removed</div>
                        </div>
                    </div>

                    <h2>Recommendations</h2>
                    <ul>
                        <li>Review any <strong>Removed</strong> pipelines to ensure they were intentionally deleted</li>
                        <li>Inspect <strong>Changed</strong> pipelines for unexpected modifications</li>
                        <li>Verify newly <strong>Added</strong> pipelines are authorized and properly configured</li>
                    </ul>

                    {action_button}

                    <table class="details-table">
                        <tr>
                            <td>Report Type:</td>
                            <td>Synapse Pipeline Checksum Verification</td>
                        </tr>
                        <tr>
                            <td>System:</td>
                            <td>{system_upper} ({environment_upper})</td>
                        </tr>
                        <tr>
                            <td>Workspace:</td>
                            <td>{workspace_name}</td>
                        </tr>
                        <tr>
                            <td>Total Checked:</td>
                            <td>{total_pipelines}</td>
                        </tr>
                    </table>
                </div>
                <div class="footer">
                    <p>This is an automated report from the ATTCC Compliance Portal.</p>
                    <p>For questions or to acknowledge findings, visit the Compliance Dashboard.</p>
                </div>
            </div>
        </body>
        </html>
        """

        action_button = ""
        if comparison_link:
            action_button = f'<a href="{comparison_link}" class="action-btn">View Detailed Report →</a>'

        html = template_html.format(
            status_emoji=status_emoji,
            status_text=status_text,
            system_upper=system.upper(),
            workspace_name=workspace_name,
            environment_upper=environment.upper(),
            run_id=run_id,
            timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
            total_pipelines=total_pipelines,
            changed_count=changed_count,
            added_count=added_count,
            removed_count=removed_count,
            action_button=action_button,
        )

        return html

    def _render_checksum_text(
        self,
        system: str,
        workspace_name: str,
        run_id: str,
        total_pipelines: int,
        changed_count: int,
        added_count: int,
        removed_count: int,
        environment: str,
        status_text: str,
        comparison_link: str | None = None,
    ) -> str:
        """Render plain text email for checksum report."""
        text = f"""
SYNAPSE CHECKSUM VERIFICATION REPORT
{"=" * 80}

Status: {status_text}
System: {system.upper()} ({environment.upper()})
Workspace: {workspace_name}
Run ID: {run_id}
Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")}

CHECKSUM STATISTICS
{"─" * 80}
Total Pipelines:  {total_pipelines}
Changed:          {changed_count}
Added:            {added_count}
Removed:          {removed_count}

RECOMMENDATIONS
{"─" * 80}
1. Review any Removed pipelines to ensure they were intentionally deleted
2. Inspect Changed pipelines for unexpected modifications
3. Verify newly Added pipelines are authorized and properly configured

DETAILS
{"─" * 80}
Report Type:      Synapse Pipeline Checksum Verification
System:           {system.upper()} ({environment.upper()})
Workspace:        {workspace_name}
Total Checked:    {total_pipelines}
"""

        if comparison_link:
            text += f"\nView Detailed Report: {comparison_link}\n"

        text += f"""
{"═" * 80}
This is an automated report from the ATTCC Compliance Portal.
For questions or to acknowledge findings, visit the Compliance Dashboard.
"""
        return text

    async def get_notification_history(
        self,
        alert_type: str | None = None,
        alert_id: int | None = None,
        status: str | None = None,
        limit: int = 100,
        exclude_alert_types: list[str] | None = None,
    ) -> list[dict[str, Any]]:
        """Get notification history."""
        if self.db is None:
            return []

        if exclude_alert_types is None and alert_type is None:
            exclude_alert_types = ["checksum_report", "checksum_verification"]

        query = select(AlertNotificationHistory)
        if alert_type:
            query = query.where(AlertNotificationHistory.alert_type == alert_type)
        if alert_id:
            query = query.where(AlertNotificationHistory.alert_id == alert_id)
        if status:
            query = query.where(AlertNotificationHistory.status == status)
        if exclude_alert_types:
            query = query.where(AlertNotificationHistory.alert_type.notin_(exclude_alert_types))

        query = query.order_by(AlertNotificationHistory.sent_at.desc()).limit(limit)
        result = await self.db.execute(query)
        history = result.scalars().all()

        return [
            {
                "id": h.id,
                "sent_at": h.sent_at.isoformat(),
                "alert_type": h.alert_type,
                "notification_type": h.alert_type,
                "alert_id": h.alert_id,
                "recipient_email": h.recipient_email,
                "subject": h.subject or self._default_subject(h.alert_type),
                "status": h.status,
                "error_message": h.error_message,
            }
            for h in history
        ]
