{{- if .Values.backend.azureKeyVaultSecrets.enabled }}
{{- range .Values.backend.azureKeyVaultSecrets.items }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ printf "%s-sync" .kubernetesSecretName | trunc 63 | trimSuffix "-" }}
spec:
  vault:
    name: {{ $.Values.backend.azureKeyVaultSecrets.vaultName | quote }}
    object:
      name: {{ .akvSecretName | quote }}
      type: {{ default "secret" .objectType | quote }}
      {{- if .objectVersion }}
      version: {{ .objectVersion | quote }}
      {{- end }}
  output:
    secret:
      name: {{ .kubernetesSecretName | quote }}
      {{- $secretType := default "Opaque" .secretType }}
      type: {{ $secretType | quote }}
      {{- if eq (lower $secretType) "opaque" }}
      dataKey: {{ default .envName .dataKey | quote }}
      {{- end }}
{{- end }}
{{- end }}
{{- if .Values.frontend.azureKeyVaultSecrets.enabled }}
{{- range .Values.frontend.azureKeyVaultSecrets.items }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ printf "%s-sync" .kubernetesSecretName | trunc 63 | trimSuffix "-" }}
spec:
  vault:
    name: {{ $.Values.frontend.azureKeyVaultSecrets.vaultName | quote }}
    object:
      name: {{ .akvSecretName | quote }}
      type: {{ default "secret" .objectType | quote }}
      {{- if .objectVersion }}
      version: {{ .objectVersion | quote }}
      {{- end }}
  output:
    secret:
      name: {{ .kubernetesSecretName | quote }}
      {{- $secretType := default "Opaque" .secretType }}
      type: {{ $secretType | quote }}
      {{- if eq (lower $secretType) "opaque" }}
      dataKey: {{ default .envName .dataKey | quote }}
      {{- end }}
{{- end }}
{{- end }}
{{- if .Values.ingress.azureKeyVaultCertificates.enabled }}
{{- range .Values.ingress.azureKeyVaultCertificates.items }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ printf "%s-sync" .kubernetesSecretName | trunc 63 | trimSuffix "-" }}
spec:
  vault:
    name: {{ $.Values.ingress.azureKeyVaultCertificates.vaultName | quote }}
    object:
      name: {{ .akvCertificateName | quote }}
      type: {{ default "certificate" .objectType | quote }}
      {{- if .objectVersion }}
      version: {{ .objectVersion | quote }}
      {{- end }}
  output:
    secret:
      name: {{ .kubernetesSecretName | quote }}
      type: "kubernetes.io/tls"
      {{- if .chainOrder }}
      chainOrder: {{ .chainOrder | quote }}
      {{- end }}
{{- end }}
{{- end }}