apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ops-portal.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "ops-portal.name" . }}
    app.kubernetes.io/component: backend
  {{- if .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.backend.serviceAccount.annotations | nindent 4 }}
  {{- end }}
