"""
SQLAlchemy MetaData with Oracle-safe naming convention and declarative Base.

Architecture section 34.2 rules implemented here:
- Constraint names are deterministic and stable across machines.
- Target ≤ 30 characters (Oracle 12c conservative limit).
- Do NOT rely on dialect truncation — all names are generated within budget.

All ORM models must subclass ``Base`` from this module so they share the
single ``metadata`` instance and automatically inherit the naming convention.

FK and problematic UQ constraints in models.py carry explicit short names
that override the convention.  PK and index names are auto-generated by the
convention and always fit within the 30-char budget for the prescribed table
names (max: ``pk_app_identifiers`` = 18 chars).
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata: MetaData = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Shared declarative base for all persistence-layer ORM models."""

    metadata = metadata
